import { StyleSheet } from 'react-native';
import { scaleSize, scaleFontSize, getMaxContainerWidth } from '../../utils/responsiveDimensions';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  backgroundImage: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: scaleSize(16),
    paddingTop: scaleSize(16),
    paddingBottom: scaleSize(8),
    minHeight: scaleSize(56),
    maxWidth: getMaxContainerWidth(),
    alignSelf: "center",
    width: "100%",
  },
  headerTitle: {
    fontSize: scaleFontSize(18),
    fontWeight: '600',
    color: '#374151',
    flex: 1,
    textAlign: 'center',
    marginHorizontal: scaleSize(8),
  },
  tripCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: scaleSize(12),
    padding: scaleSize(16),
    marginBottom: scaleSize(12),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: scaleSize(2) },
    shadowOpacity: 0.1,
    shadowRadius: scaleSize(4),
    elevation: 3,
    minHeight: scaleSize(120),
  },
  cityText: {
    fontSize: scaleFontSize(14),
    fontWeight: '600',
    color: '#374151',
    flex: 1,
    textAlign: 'center',
  },
  priceText: {
    fontSize: scaleFontSize(18),
    fontWeight: '700',
    color: '#10B981',
    minWidth: scaleSize(80),
    textAlign: 'right',
  },
  selectButton: {
    backgroundColor: '#3B82F6',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: scaleSize(16),
    paddingVertical: scaleSize(8),
    borderRadius: scaleSize(12),
    marginLeft: scaleSize(8),
  },
  backButton: {
    padding: scaleSize(8),
    minWidth: scaleSize(40),
  },
  placeholder: {
    width: scaleSize(40),
  },
  progressContainer: {
    backgroundColor: '#F0F9FF',
    marginHorizontal: scaleSize(16),
    marginBottom: scaleSize(8),
    borderRadius: scaleSize(8),
    padding: scaleSize(16),
    borderWidth: 1,
    borderColor: '#3B82F6',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: scaleSize(2) },
    shadowOpacity: 0.1,
    shadowRadius: scaleSize(4),
    elevation: 3,
    maxWidth: getMaxContainerWidth(),
    alignSelf: "center",
    width: "100%",
  },
  progressSteps: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  progressStep: {
    backgroundColor: '#F3F4F6',
    borderRadius: scaleSize(20),
    paddingHorizontal: scaleSize(16),
    paddingVertical: scaleSize(8),
    minWidth: scaleSize(80),
    alignItems: 'center',
  },
  progressStepActive: {
    backgroundColor: '#3B82F6',
  },
  progressStepCompleted: {
    backgroundColor: '#10B981',
  },
  progressStepText: {
    fontSize: scaleFontSize(14),
    fontWeight: '600',
    color: '#6B7280',
  },
  progressStepTextActive: {
    color: 'white',
  },
  progressStepTextCompleted: {
    color: 'white',
  },
  progressLine: {
    width: scaleSize(40),
    height: scaleSize(2),
    backgroundColor: '#E5E7EB',
    marginHorizontal: scaleSize(8),
  },
  summaryCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    margin: scaleSize(16),
    padding: scaleSize(16),
    borderRadius: scaleSize(12),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: scaleSize(2) },
    shadowOpacity: 0.1,
    shadowRadius: scaleSize(4),
    elevation: 3,
    maxWidth: getMaxContainerWidth(),
    alignSelf: "center",
    width: "100%",
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: scaleSize(8),
    minHeight: scaleSize(20),
  },
  summaryLabel: {
    fontSize: scaleFontSize(14),
    color: '#6B7280',
    fontWeight: '500',
    minWidth: scaleSize(80),
  },
  summaryValue: {
    fontSize: scaleFontSize(14),
    color: '#374151',
    fontWeight: '600',
    flex: 1,
    textAlign: 'right',
    marginLeft: scaleSize(8),
  },
  scrollView: {
    flex: 1,
  },
  scrollViewContent: {
    paddingHorizontal: scaleSize(16),
    paddingBottom: scaleSize(20),
  },
  loadingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: scaleSize(60),
  },
  loadingText: {
    fontSize: scaleFontSize(16),
    color: '#6B7280',
    marginTop: scaleSize(16),
    textAlign: 'center',
  },
  tripsContainer: {
    paddingVertical: scaleSize(8),
    maxWidth: getMaxContainerWidth(),
    alignSelf: "center",
    width: "100%",
  },
  resultsTitle: {
    fontSize: scaleFontSize(18),
    fontWeight: '600',
    color: '#374151',
    marginBottom: scaleSize(16),
    textAlign: 'center',
  },
  tripHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: scaleSize(12),
  },
  routeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: scaleSize(8),
  },
  arrowIcon: {
    marginHorizontal: scaleSize(4),
  },
  tripDetails: {
    gap: scaleSize(12),
  },
  timeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  timeInfo: {
    alignItems: 'center',
    flex: 1,
  },
  timeLabel: {
    fontSize: scaleFontSize(11),
    color: '#6B7280',
    marginBottom: scaleSize(4),
  },
  timeText: {
    fontSize: scaleFontSize(12),
    fontWeight: '600',
    color: '#374151',
    textAlign: 'center',
  },
  durationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: scaleSize(8),
    flex: 0.8,
  },
  durationText: {
    fontSize: scaleFontSize(11),
    color: '#6B7280',
    marginLeft: scaleSize(4),
  },
  bottomRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: scaleSize(4),
  },
  availabilityContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  availabilityText: {
    fontSize: scaleFontSize(12),
    fontWeight: '500',
    marginLeft: scaleSize(6),
  },
  selectButtonText: {
    fontSize: scaleFontSize(14),
    fontWeight: '600',
    color: 'white',
    marginLeft: scaleSize(6),
  },
  loadMoreButton: {
    backgroundColor: '#ffffff',
    paddingVertical: scaleSize(16),
    paddingHorizontal: scaleSize(24),
    borderRadius: scaleSize(12),
    marginTop: scaleSize(16),
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#a6a6a6',
  },
  loadMoreContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadMoreText: {
    fontSize: scaleFontSize(16),
    fontWeight: '600',
    color: '#a6a6a6',
    marginLeft: scaleSize(8),
  },
  emptyStateContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: scaleSize(60),
    paddingHorizontal: scaleSize(32),
  },
  emptyStateTitle: {
    fontSize: scaleFontSize(20),
    fontWeight: '600',
    color: '#374151',
    marginTop: scaleSize(16),
    marginBottom: scaleSize(8),
    textAlign: 'center',
  },
  emptyStateMessage: {
    fontSize: scaleFontSize(16),
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: scaleSize(24),
    marginBottom: scaleSize(24),
  },
  errorContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: scaleSize(60),
    paddingHorizontal: scaleSize(32),
  },
  errorTitle: {
    fontSize: scaleFontSize(20),
    fontWeight: '600',
    color: '#374151',
    marginTop: scaleSize(16),
    marginBottom: scaleSize(8),
    textAlign: 'center',
  },
  errorMessage: {
    fontSize: scaleFontSize(16),
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: scaleSize(24),
    marginBottom: scaleSize(24),
  },
  retryButton: {
    backgroundColor: '#3B82F6',
    paddingHorizontal: scaleSize(24),
    paddingVertical: scaleSize(12),
    borderRadius: scaleSize(8),
  },
  retryButtonText: {
    fontSize: scaleFontSize(16),
    fontWeight: '600',
    color: 'white',
  },
});