import { StyleSheet, Dimensions } from 'react-native';
import { scaleSize, scaleFontSize } from '../../utils/responsiveDimensions';

const { width: screenWidth, height: screenHeight } = Dimensions.get('window');

export const styles = StyleSheet.create({
  downloadButtonCanceled: {
    opacity: 0.3,
  },
  ticketCard: {
    backgroundColor: 'white',
    borderRadius: scaleSize(12),
    padding: scaleSize(16),
    marginBottom: scaleSize(12),
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: scaleSize(1) },
    shadowOpacity: 0.1,
    shadowRadius: scaleSize(2),
  },
  ticketHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: scaleSize(16),
  },
  ticketTitleContainer: {
    flex: 1,
    gap: scaleSize(8),
  },
  ticketTitle: {
    fontSize: scaleFontSize(16),
    fontWeight: '600',
    color: '#374151',
  },
  ticketStatusBadge: {
    paddingHorizontal: scaleSize(8),
    paddingVertical: scaleSize(4),
    borderRadius: scaleSize(12),
    alignSelf: 'flex-start',
  },
  ticketStatusText: {
    color: 'white',
    fontSize: scaleFontSize(12),
    fontWeight: '600',
  },
  ticketPricing: {
    backgroundColor: '#F8F9FA',
    borderRadius: scaleSize(8),
    padding: scaleSize(12),
    marginBottom: scaleSize(12),
  },
  pricingGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: scaleSize(12),
  },
  pricingItem: {
    flex: 1,
    minWidth: '45%',
  },
  subtotalText: {
    color: '#3B82F6',
  },
  ticketFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  ticketDate: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scaleSize(6),
    flex: 1,
  },
  ticketDateText: {
    fontSize: scaleFontSize(12),
    color: '#9E9E9E',
  },
  downloadTicketButton: {
    padding: scaleSize(8),
    borderRadius: scaleSize(20),
    backgroundColor: '#F3F4F6',
    marginLeft: scaleSize(8),
    minWidth: scaleSize(36),
    minHeight: scaleSize(36),
    justifyContent: 'center',
    alignItems: 'center',
  },
  container: {
    flex: 1,
  },
  backgroundImage: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  scrollView: {
    flex: 1,
    width: "100%",
  },
  scrollViewContent: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
  },
  cardContainer: {
    width: "100%",
    maxWidth: 600,
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    borderRadius: 16,
    padding: 24,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    alignSelf: 'center',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  backButton: {
    padding: 8,
    borderRadius: 20,
  },
  headerTitle: {
    fontSize: Math.min(screenWidth * 0.05, 20),
    fontWeight: '600',
    color: '#374151',
    flex: 1,
    textAlign: 'center',
  },
  headerRightButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  downloadButton: {
    padding: 8,
    borderRadius: 20,
  },
  downloadButtonDisabled: {
    opacity: 0.5,
  },
  homeButton: {
    padding: 8,
    borderRadius: 20,
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    minHeight: screenHeight * 0.6,
  },
  errorContainer: {
    alignItems: 'center',
    maxWidth: screenWidth * 0.8,
  },
  loadingText: {
    fontSize: 16,
    color: '#6B7280',
    marginTop: 16,
    textAlign: 'center',
  },
  errorTitle: {
    fontSize: Math.min(screenWidth * 0.05, 20),
    fontWeight: '600',
    color: '#374151',
    marginTop: 16,
    textAlign: 'center',
  },
  errorMessage: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
    marginTop: 8,
    marginBottom: 24,
    lineHeight: 20,
  },
  errorButtonsContainer: {
    flexDirection: screenWidth > 400 ? 'row' : 'column',
    gap: 12,
    width: '100%',
  },
  retryButton: {
    backgroundColor: '#3B82F6',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    flex: screenWidth > 400 ? 1 : 0,
  },
  retryButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
  goBackButton: {
    backgroundColor: '#6B7280',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    flex: screenWidth > 400 ? 1 : 0,
  },
  goBackButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: Math.min(screenWidth * 0.045, 18),
    fontWeight: '600',
    color: '#374151',
    marginBottom: 12,
  },
  headerCard: {
    backgroundColor: 'white',
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  statusContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    gap: 6,
  },
  statusText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '600',
  },
  purchaseId: {
    fontSize: 16,
    fontWeight: '600',
    color: '#6B7280',
  },
  statusDescriptionContainer: {
    marginBottom: 16,
  },
  statusDescription: {
    fontSize: 14,
    fontWeight: '500',
    textAlign: 'center',
  },
  priceSection: {
    alignItems: 'center',
    marginBottom: 16,
  },
  totalLabel: {
    fontSize: 14,
    color: '#6B7280',
    marginBottom: 4,
  },
  totalPrice: {
    fontSize: Math.min(screenWidth * 0.08, 32),
    fontWeight: 'bold',
    color: '#374151',
  },
  originalPrice: {
    fontSize: 14,
    color: '#9E9E9E',
    textDecorationLine: 'line-through',
    marginTop: 4,
  },
  dateSection: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  dateText: {
    fontSize: 14,
    color: '#6B7280',
  },
  infoCard: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 16,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  infoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  infoItem: {
    flex: screenWidth > 400 ? 1 : 0,
    minWidth: screenWidth > 400 ? 0 : '45%',
  },
  infoLabel: {
    fontSize: 12,
    color: '#9E9E9E',
    marginBottom: 4,
    textTransform: 'uppercase',
    fontWeight: '500',
  },
  infoValue: {
    fontSize: 16,
    color: '#374151',
    fontWeight: '600',
  },
  seatContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E3F2FD',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    gap: 4,
  },
  seatNumber: {
    fontSize: 14,
    fontWeight: '600',
    color: '#3B82F6',
  },
  routeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    paddingHorizontal: 8,
  },
  routeItem: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 8,
  },
  routeText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#374151',
    flex: 1,
  },
  routeArrow: {
    paddingHorizontal: 8,
  },
  pricingLabel: {
    fontSize: 12,
    color: '#6B7280',
    marginBottom: 2,
  },
  pricingValue: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
  },
  discountText: {
    color: '#4CAF50',
  },
  refundText: {
    color: '#FF9800',
  },
});