import { StyleSheet, Platform } from 'react-native';
import { scaleSize, scaleFontSize, getResponsivePadding, getMaxContainerWidth } from '../../utils/responsiveDimensions';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  backgroundImage: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  keyboardAvoidingView: {
    flex: 1,
    width: "100%",
  },
  contentContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: scaleSize(16),
  },
  cardContainer: {
    width: "100%",
    maxWidth: getMaxContainerWidth(),
    alignSelf: "center",
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    borderRadius: scaleSize(16),
    padding: getResponsivePadding(),
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: scaleSize(4),
    },
    shadowOpacity: 0.3,
    shadowRadius: scaleSize(8),
    elevation: 8,
  },
  headerContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: scaleSize(32),
  },
  backButton: {
    padding: scaleSize(8),
    minWidth: scaleSize(40),
    minHeight: scaleSize(40),
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: scaleFontSize(20),
    fontWeight: "600",
    color: "#374151",
    textAlign: "center",
  },
  placeholder: {
    width: scaleSize(40),
  },
  iconContainer: {
    alignItems: "center",
    marginBottom: scaleSize(32),
  },
  emailIconCircle: {
    width: scaleSize(80),
    height: scaleSize(80),
    backgroundColor: "#EBF4FF",
    borderRadius: scaleSize(40),
    justifyContent: "center",
    alignItems: "center",
    marginBottom: scaleSize(16),
  },
  mainTitle: {
    fontSize: scaleFontSize(24),
    fontWeight: "bold",
    color: "#1F2937",
    marginBottom: scaleSize(8),
  },
  subtitle: {
    fontSize: scaleFontSize(16),
    color: "#6B7280",
    textAlign: "center",
    marginBottom: scaleSize(8),
    lineHeight: scaleFontSize(22),
  },
  emailText: {
    fontSize: scaleFontSize(14),
    color: "#3B82F6",
    fontWeight: "500",
  },
  formContainer: {
    width: "100%",
  },
  inputContainer: {
    marginBottom: scaleSize(24),
    width: "100%",
  },
  inputLabel: {
    fontSize: scaleFontSize(14),
    fontWeight: "500",
    color: "#4B5563",
    marginBottom: scaleSize(8),
    textAlign: "center",
  },
  codeInput: {
    backgroundColor: "white",
    height: scaleSize(60),
    borderRadius: scaleSize(8),
    borderWidth: 1,
    borderColor: "#D1D5DB",
    paddingHorizontal: scaleSize(16),
    fontSize: scaleFontSize(24),
    color: "#1F2937",
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    letterSpacing: scaleSize(8),
    marginBottom: scaleSize(8),
  },
  inputError: {
    borderColor: "#EF4444",
    borderWidth: 2,
  },
  helperText: {
    fontSize: scaleFontSize(12),
    color: "#6B7280",
    textAlign: "center",
    lineHeight: scaleFontSize(16),
  },
  errorText: {
    color: "#EF4444",
    fontSize: scaleFontSize(12),
    marginTop: scaleSize(4),
    textAlign: "center",
  },
  verifyButton: {
    backgroundColor: "#3B82F6",
    height: scaleSize(50),
    borderRadius: scaleSize(12),
    justifyContent: "center",
    alignItems: "center",
    marginBottom: scaleSize(16),
    shadowColor: "#3B82F6",
    shadowOffset: {
      width: 0,
      height: scaleSize(2),
    },
    shadowOpacity: 0.3,
    shadowRadius: scaleSize(4),
    elevation: 4,
  },
  verifyButtonDisabled: {
    backgroundColor: "#9CA3AF",
    shadowOpacity: 0,
    elevation: 0,
  },
  verifyButtonText: {
    color: "white",
    fontSize: scaleFontSize(16),
    fontWeight: "600",
  },
  expirationText: {
    fontSize: scaleFontSize(12),
    color: "#6B7280",
    textAlign: "center",
  },
});