import { StyleSheet } from 'react-native';
import { scaleSize, scaleFontSize, getResponsivePadding, getMaxContainerWidth } from '../../utils/responsiveDimensions';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  backgroundImage: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  scrollView: {
    flex: 1,
    width: "100%",
  },
  scrollViewContent: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: scaleSize(16),
  },
  cardContainer: {
    width: "100%",
    maxWidth: getMaxContainerWidth(),
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    borderRadius: scaleSize(16),
    padding: getResponsivePadding(),
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: scaleSize(4),
    },
    shadowOpacity: 0.3,
    shadowRadius: scaleSize(8),
    elevation: 8,
    alignSelf: 'center',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: scaleSize(24),
  },
  backButton: {
    padding: scaleSize(8),
    borderRadius: scaleSize(20),
    minWidth: scaleSize(40),
    minHeight: scaleSize(40),
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: scaleFontSize(20),
    fontWeight: '600',
    color: '#374151',
    flex: 1,
    textAlign: 'center',
  },
  headerRightButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scaleSize(8),
  },
  downloadButton: {
    padding: scaleSize(8),
    borderRadius: scaleSize(20),
    minWidth: scaleSize(40),
    minHeight: scaleSize(40),
    justifyContent: 'center',
    alignItems: 'center',
  },
  downloadButtonDisabled: {
    opacity: 0.5,
  },
  homeButton: {
    padding: scaleSize(8),
    borderRadius: scaleSize(20),
    minWidth: scaleSize(40),
    minHeight: scaleSize(40),
    justifyContent: 'center',
    alignItems: 'center',
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: scaleSize(20),
  },
  errorContainer: {
    alignItems: 'center',
    maxWidth: '80%',
  },
  loadingText: {
    fontSize: scaleFontSize(16),
    color: '#6B7280',
    marginTop: scaleSize(16),
    textAlign: 'center',
  },
  errorTitle: {
    fontSize: scaleFontSize(20),
    fontWeight: '600',
    color: '#374151',
    marginTop: scaleSize(16),
    textAlign: 'center',
  },
  errorMessage: {
    fontSize: scaleFontSize(14),
    color: '#6B7280',
    textAlign: 'center',
    marginTop: scaleSize(8),
    marginBottom: scaleSize(24),
    lineHeight: scaleFontSize(20),
  },
  errorButtonsContainer: {
    flexDirection: 'column',
    gap: scaleSize(12),
    width: '100%',
  },
  retryButton: {
    backgroundColor: '#3B82F6',
    paddingHorizontal: scaleSize(24),
    paddingVertical: scaleSize(12),
    borderRadius: scaleSize(8),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: scaleSize(8),
  },
  retryButtonText: {
    color: 'white',
    fontSize: scaleFontSize(16),
    fontWeight: '600',
  },
  goBackButton: {
    backgroundColor: '#6B7280',
    paddingHorizontal: scaleSize(24),
    paddingVertical: scaleSize(12),
    borderRadius: scaleSize(8),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: scaleSize(8),
  },
  goBackButtonText: {
    color: 'white',
    fontSize: scaleFontSize(16),
    fontWeight: '600',
  },
  section: {
    marginBottom: scaleSize(24),
  },
  sectionTitle: {
    fontSize: scaleFontSize(18),
    fontWeight: '600',
    color: '#374151',
    marginBottom: scaleSize(12),
  },
  headerCard: {
    backgroundColor: 'white',
    borderRadius: scaleSize(16),
    padding: scaleSize(20),
    marginBottom: scaleSize(24),
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: scaleSize(1) },
    shadowOpacity: 0.1,
    shadowRadius: scaleSize(2),
  },
  statusContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: scaleSize(12),
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: scaleSize(12),
    paddingVertical: scaleSize(6),
    borderRadius: scaleSize(16),
    gap: scaleSize(6),
  },
  statusText: {
    color: 'white',
    fontSize: scaleFontSize(14),
    fontWeight: '600',
  },
  ticketId: {
    fontSize: scaleFontSize(16),
    fontWeight: '600',
    color: '#6B7280',
  },
  statusDescriptionContainer: {
    marginBottom: scaleSize(16),
  },
  statusDescription: {
    fontSize: scaleFontSize(14),
    fontWeight: '500',
    textAlign: 'center',
  },
  priceSection: {
    alignItems: 'center',
    marginBottom: scaleSize(16),
  },
  totalLabel: {
    fontSize: scaleFontSize(14),
    color: '#6B7280',
    marginBottom: scaleSize(4),
  },
  totalPrice: {
    fontSize: scaleFontSize(32),
    fontWeight: 'bold',
    color: '#374151',
  },
  originalPrice: {
    fontSize: scaleFontSize(14),
    color: '#9E9E9E',
    textDecorationLine: 'line-through',
    marginTop: scaleSize(4),
  },
  dateSection: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: scaleSize(8),
  },
  dateText: {
    fontSize: scaleFontSize(14),
    color: '#6B7280',
  },
  infoCard: {
    backgroundColor: 'white',
    borderRadius: scaleSize(12),
    padding: scaleSize(16),
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: scaleSize(1) },
    shadowOpacity: 0.1,
    shadowRadius: scaleSize(2),
  },
  routeContainer: {
    marginBottom: scaleSize(20),
  },
  routeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: scaleSize(12),
    gap: scaleSize(8),
  },
  routeTitle: {
    fontSize: scaleFontSize(16),
    fontWeight: '600',
    color: '#374151',
  },
  routeDetails: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: scaleSize(8),
  },
  routePoint: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: scaleSize(8),
  },
  routeText: {
    fontSize: scaleFontSize(14),
    fontWeight: '500',
    color: '#374151',
    flex: 1,
  },
  routeArrow: {
    paddingHorizontal: scaleSize(8),
  },
  seatContainer: {
    marginBottom: scaleSize(20),
  },
  seatHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: scaleSize(12),
    gap: scaleSize(8),
  },
  seatTitle: {
    fontSize: scaleFontSize(16),
    fontWeight: '600',
    color: '#374151',
  },
  seatBadge: {
    backgroundColor: '#E3F2FD',
    borderRadius: scaleSize(8),
    paddingHorizontal: scaleSize(16),
    paddingVertical: scaleSize(8),
    alignSelf: 'flex-start',
  },
  seatNumber: {
    fontSize: scaleFontSize(18),
    fontWeight: '700',
    color: '#3B82F6',
  },
  infoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: scaleSize(16),
  },
  infoItem: {
    flex: 1,
    minWidth: '45%',
  },
  infoLabel: {
    fontSize: scaleFontSize(12),
    color: '#9E9E9E',
    marginBottom: scaleSize(4),
    textTransform: 'uppercase',
    fontWeight: '500',
  },
  infoValue: {
    fontSize: scaleFontSize(16),
    color: '#374151',
    fontWeight: '600',
  },
  pricingCard: {
    backgroundColor: 'white',
    borderRadius: scaleSize(12),
    padding: scaleSize(16),
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: scaleSize(1) },
    shadowOpacity: 0.1,
    shadowRadius: scaleSize(2),
  },
  pricingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: scaleSize(8),
  },
  pricingLabel: {
    fontSize: scaleFontSize(14),
    color: '#6B7280',
  },
  pricingValue: {
    fontSize: scaleFontSize(16),
    fontWeight: '600',
    color: '#374151',
  },
  discountText: {
    color: '#F44336',
  },
  totalText: {
    color: '#4CAF50',
    fontSize: scaleFontSize(18),
  },
  refundText: {
    color: '#FF9800',
  },
  pricingDivider: {
    height: 1,
    backgroundColor: '#E5E7EB',
    marginVertical: scaleSize(8),
  },
  refundDateContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scaleSize(6),
    marginTop: scaleSize(8),
    paddingTop: scaleSize(8),
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
  },
  refundDateText: {
    fontSize: scaleFontSize(12),
    color: '#2196F3',
    fontStyle: 'italic',
  },
});