import { StyleSheet } from 'react-native';
import { scaleSize, scaleFontSize, getResponsivePadding, getMaxContainerWidth } from '../../utils/responsiveDimensions';

export const styles = StyleSheet.create({

  conductorHeader: {
    backgroundColor: '#374151',
    borderTopLeftRadius: scaleSize(16),
    borderTopRightRadius: scaleSize(16),
    paddingVertical: scaleSize(12),
    paddingHorizontal: scaleSize(16),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: -scaleSize(15),
    marginTop: -scaleSize(16),
    marginBottom: scaleSize(16),
  },
  volante: {
    alignItems: 'center',
    marginLeft: scaleSize(6),
    flexDirection: 'row',
  },
  puertaIndicator: {
    backgroundColor: '#10B981',
    borderRadius: scaleSize(4),
    paddingHorizontal: scaleSize(8),
    paddingVertical: scaleSize(4),
    flexDirection: 'row',
    alignItems: 'center',
  },
  busShape: {
    borderWidth: 2,
    borderColor: '#374151',
    borderRadius: scaleSize(20),
    padding: scaleSize(12),
    backgroundColor: '#F3F4F6',
    alignSelf: 'center',
    width: '100%', 
    maxWidth: scaleSize(304),
    position: 'relative',
  },
  asientosContainer: {
    gap: scaleSize(6),
    width: '100%',
    paddingHorizontal: scaleSize(4),
  },
  fila: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: scaleSize(6),
    marginBottom: scaleSize(6),
    paddingHorizontal: scaleSize(4),
  },
  asiento: {
    width: scaleSize(36),
    height: scaleSize(36),
    borderRadius: scaleSize(6),
    justifyContent: 'center',
    alignItems: 'center',
    margin: scaleSize(1),
    borderWidth: 1,
  },
  asientoVacio: {
    width: scaleSize(36),
    height: scaleSize(36),
    margin: scaleSize(1),
  },
  filaNumber: {
    width: scaleSize(20),
    height: scaleSize(20),
    backgroundColor: '#6B7280',
    borderRadius: scaleSize(10),
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: scaleSize(8),
  },
  filaNumberText: {
    fontSize: scaleFontSize(10),
    color: '#FFFFFF',
    fontWeight: '600',
  },
  numeroAsiento: {
    fontSize: 12,
    fontWeight: '600',
    color: '#1F2937',
  },
  conductorText: {
    fontSize: scaleFontSize(12),
    color: '#FFFFFF',
    fontWeight: '600',
    textTransform: 'uppercase',
    marginLeft: scaleSize(8),
  },
  puertaText: {
    fontSize: scaleFontSize(12),
    color: '#FFFFFF',
    fontWeight: '600',
    marginLeft: scaleSize(4),
  },
  filaSeats: {
    flexDirection: 'row',
    gap: scaleSize(8),
    flex: 1,
    justifyContent: 'space-between',
  },
  asientoDisponible: {
    borderColor: '#10B981',
    backgroundColor: '#10B981',
  },
  asientoSeleccionado: {
    borderColor: '#3B82F6',
    backgroundColor: '#3B82F6',
  },
  asientoOcupado: {
    borderColor: '#9CA3AF',
    backgroundColor: '#9CA3AF',
  },
  asientoReservado: {
    borderColor: '#9CA3AF',
    backgroundColor: '#9CA3AF',
  },
  numeroAsientoSeleccionado: {
    color: '#FFFFFF',
  },
  numeroAsientoGris: {
    color: '#FFFFFF',
  },
  busFooter: {
    backgroundColor: '#374151',
    borderBottomLeftRadius: scaleSize(16),
    borderBottomRightRadius: scaleSize(16),
    paddingVertical: scaleSize(12),
    paddingHorizontal: scaleSize(16),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: -scaleSize(15),
    marginBottom: -scaleSize(16),
    marginTop: scaleSize(16),
  },
  emergencyText: {
    fontSize: scaleFontSize(12),
    color: '#FFFFFF',
    fontWeight: '600',
    textTransform: 'uppercase',
    marginLeft: scaleSize(8),
  },
  legendContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: scaleSize(20),
    paddingHorizontal: scaleSize(16),
    gap: scaleSize(20),
    backgroundColor: '#FFFFFF',
    borderRadius: scaleSize(8),
    paddingVertical: scaleSize(12),
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scaleSize(8),
  },
  legendSeat: {
    width: scaleSize(20),
    height: scaleSize(20),
    borderWidth: 2,
    borderRadius: scaleSize(4),
  },
  legendText: {
    fontSize: scaleFontSize(12),
    color: '#374151',
    fontWeight: '500',
  },
  container: {
    flex: 1,
  },
  cardContainer: {
    width: "100%",
    maxWidth: getMaxContainerWidth(),
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    borderRadius: scaleSize(16),
    padding: getResponsivePadding(),
    shadowColor: "#000",
    shadowOffset: { width: 0, height: scaleSize(4) },
    shadowOpacity: 0.3,
    shadowRadius: scaleSize(8),
    elevation: 8,
    alignSelf: 'center',
  },
  finalizarButton: {
    backgroundColor: '#3B82F6',
    borderRadius: scaleSize(12),
    paddingVertical: scaleSize(16),
    alignItems: 'center',
  },
  finalizarButtonText: {
    color: 'white',
    fontSize: scaleFontSize(18),
    fontWeight: '600',
  },
  backgroundImage: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollViewContent: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
  },
  loadingText: {
    fontSize: 16,
    color: '#6B7280',
    marginTop: 16,
    textAlign: 'center',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
  },
  errorTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#374151',
    marginTop: 16,
    marginBottom: 8,
    textAlign: 'center',
  },
  errorMessage: {
    fontSize: 16,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 24,
  },
  retryButton: {
    backgroundColor: '#3B82F6',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
  },
  retryButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: 'white',
  },
  headerContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 24,
  },
  backButton: {
    padding: 8,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: "#374151",
    textAlign: "center",
  },
  placeholder: {
    width: 40,
  },
  progressContainer: {
    backgroundColor: '#F0F9FF',
    borderRadius: 8,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#3B82F6',
  },
  progressSteps: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  progressStep: {
    backgroundColor: '#F3F4F6',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 8,
    minWidth: 80,
    alignItems: 'center',
  },
  progressStepActive: {
    backgroundColor: '#3B82F6',
  },
  progressStepCompleted: {
    backgroundColor: '#10B981',
  },
  progressStepText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6B7280',
  },
  progressStepTextActive: {
    color: 'white',
  },
  progressStepTextCompleted: {
    color: 'white',
  },
  progressLine: {
    width: 40,
    height: 2,
    backgroundColor: '#E5E7EB',
    marginHorizontal: 8,
  },
  tripInfoContainer: {
    backgroundColor: "#ECFDF5",
    borderRadius: 8,
    padding: 16,
    borderWidth: 1,
    borderColor: "#10B981",
    marginBottom: 20,
  },
  tripInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  tripInfoText: {
    fontSize: 14,
    color: '#10B981',
    marginLeft: 8,
    flex: 1,
  },
  selectedSeatsContainer: {
    backgroundColor: "#EBF4FF",
    borderRadius: 8,
    padding: 16,
    borderWidth: 1,
    borderColor: "#4285F4",
    marginBottom: 20,
  },
  selectedSeatsTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#1E40AF",
    marginBottom: 12,
  },
  selectedSeatsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  selectedSeatBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#DBEAFE',
    borderColor: '#4285F4',
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  selectedSeatNumber: {
    fontSize: 12,
    fontWeight: '600',
    color: '#4285F4',
    marginLeft: 4,
  },
  busSection: {
    marginBottom: 20,
  },
  busSectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#374151",
    textAlign: "center",
    marginBottom: 16,
  },
  refreshButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F0FDF4',
    borderColor: '#3B82F6',
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  refreshButtonText: {
    fontSize: 14,
    color: '#3B82F6',
    fontWeight: '600',
    marginLeft: 8,
  },
  footerSection: {
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    paddingTop: 16,
  },
  desglosePrecio: {
    backgroundColor: '#F9FAFB',
    borderRadius: 8,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  lineaPrecio: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  lineaDescuento: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  lineaTotal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
  },
  labelPrecio: {
    fontSize: 14,
    color: '#374151',
    flex: 1,
  },
  valorPrecio: {
    fontSize: 14,
    color: '#374151',
    fontWeight: '500',
  },
  labelDescuento: {
    fontSize: 14,
    color: '#374151',
    flex: 1,
  },
  valorDescuento: {
    fontSize: 14,
    color: '#F44336',
    fontWeight: '500',
  },
  labelTotal: {
    fontSize: 16,
    color: '#374151',
    fontWeight: 'bold',
    flex: 1,
  },
  valorTotal: {
    fontSize: 18,
    color: '#10B981',
    fontWeight: '700',
  },
  separador: {
    height: 1,
    backgroundColor: '#E5E7EB',
    marginVertical: 8,
  },
  finalizarButtonDisabled: {
    backgroundColor: '#9CA3AF',
  },
});